### ISSUE TITLE
It's awesome you have this repo, but can you give attention to and respond in delete-older-releases?

### ISSUE THREAD

**Issue by thadguidry** [dev-drprasad/chrome-tab-switch#1]
Hi @dev-drprasad we asked you in a DM on Twitter and sent an email I think if I found the right one... if you intended to continue to maintain delete-older-releases and delete-tag-and-release.  If not, it would be great to mention this and allow the community to maintain it further.  This can be done in a number of ways:

1. Allow PR's to be reviewed and merged into master by OTHER trusted contributors (perhaps such as @smallprogram who made a useful fork and [change thus far](https://github.com/dev-drprasad/delete-older-releases/compare/master...smallprogram:delete-older-releases:master)) - change the settings in the GitHub repo and setup the master branch as "protected".
2. Update the README.md to ask for someone to step in as a maintainer and help you or to take over the project.
3. ???

**Comment by smallprogram** [comment]
I don't quite understand what you mean, what do I need to do?

**Comment by thadguidry** [comment]
@smallprogram I was talking to @dev-drprasad and only mentioning you as an example to him that the community could help maintain the project if he does not want to.

**Comment by smallprogram** [comment]
> @smallprogram I was talking to @dev-drprasad and only mentioning you as an example to him that the community could help maintain the project if he does not want to.

OK👌

**Comment by dev-drprasad** [comment]
@thadguidry  Invited you as collaborator

**Comment by thadguidry** [comment]
@dev-drprasad Thanks so much!  We've pushed a new release with a few updates!
I'll close this issue now that we have collaboration in your other repo.
